extern crate vy_core as vy;

use vy_macros::declare_elements;

declare_elements!(
    a {},
    animate {},
    animateMotion {},
    animateTransform {},
    circle {},
    clipPath {},
    defs {},
    desc {},
    ellipse {},
    feBlend {},
    feColorMatrix {},
    feComponentTransfer {},
    feComposite {},
    feConvolveMatrix {},
    feDiffuseLighting {},
    feDisplacementMap {},
    feDistantLight {},
    feDropShadow {},
    feFlood {},
    feFuncA {},
    feFuncB {},
    feFuncG {},
    feFuncR {},
    feGaussianBlur {},
    feImage {},
    feMerge {},
    feMergeNode {},
    feMorphology {},
    feOffset {},
    fePointLight {},
    feSpecularLighting {},
    feSpotLight {},
    feTile {},
    feTurbulence {},
    filter {},
    foreignObject {},
    g {},
    image {},
    line {},
    linearGradient {},
    marker {},
    mask {},
    metadata {},
    mpath {},
    path {},
    pattern {},
    polygon {},
    polyline {},
    radialGradient {},
    rect {},
    script {
        crossorigin,
        href,
        r#type,
    },
    set {},
    stop {},
    style {},
    svg {},
    switch {},
    symbol {},
    text {},
    textPath {},
    title {},
    tspan {},
    r#use {},
    view {},
);
