[package]
name = "vy-core"
version = "0.3.0"
edition = "2024"
authors = ["Jonah Lund <jonahlund@proton.me>"]
description = """
Small, simple and fast HTML templating library.
"""
repository = "https://github.com/JonahLund/vy"
keywords = ["html", "macros", "template"]
categories = ["template-engine", "web-programming"]
license = "MIT"
workspace = "../"

[features]
std = []
nightly = []

[dependencies]
itoap = "1.0.1"
ryu = "1"

[dev-dependencies]
vy = { path = "../" }
