[package]
name = "vy-macros"
version = "0.3.0"
edition = "2024"
authors = ["Jonah Lund <jonahlund@proton.me>"]
description = """
Small, simple and fast HTML templating library.
"""
repository = "https://github.com/JonahLund/vy"
keywords = ["html", "macros", "template"]
categories = ["template-engine", "web-programming"]
license = "MIT"
workspace = "../"

[lib]
proc-macro = true

[features]
well-known = []

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
vy-core = { path = "../core", version = "0.3.0" }

[dev-dependencies]
vy = { path = "../" }
